const root = 'https://roaakdm.com';
const directory = 'flutter-gallery-example/hd';

const List<String> images = [
  '$root/$directory/paris-01.jpeg',
  '$root/$directory/paris-02.jpeg',
  '$root/$directory/paris-03.jpeg',
  '$root/$directory/paris-04.jpeg',
  '$root/$directory/paris-05.jpeg',
  '$root/$directory/paris-06.jpeg',
  '$root/$directory/paris-07.jpeg',
  '$root/$directory/paris-08.jpeg',
  '$root/$directory/paris-09.jpeg',
  '$root/$directory/paris-10.jpeg',
  '$root/$directory/paris-11.jpeg',
  '$root/$directory/paris-12.jpeg',
  '$root/$directory/paris-13.jpeg',
  '$root/$directory/paris-14.jpeg',
  '$root/$directory/paris-15.jpeg',
  '$root/$directory/paris-16.jpeg',
  '$root/$directory/paris-17.jpeg',
  '$root/$directory/paris-18.jpeg',
  '$root/$directory/paris-19.jpeg',
  '$root/$directory/paris-20.jpeg',
  '$root/$directory/paris-21.jpeg',
  '$root/$directory/paris-22.jpeg',
  '$root/$directory/paris-23.jpeg',
  '$root/$directory/paris-24.jpeg',
  '$root/$directory/paris-25.jpeg',
  '$root/$directory/florence-01.jpeg',
  '$root/$directory/florence-02.jpeg',
  '$root/$directory/florence-03.jpeg',
  '$root/$directory/florence-04.jpeg',
  '$root/$directory/florence-05.jpeg',
  '$root/$directory/florence-06.jpeg',
  '$root/$directory/florence-07.jpeg',
  '$root/$directory/florence-08.jpeg',
  '$root/$directory/florence-09.jpeg',
  '$root/$directory/florence-10.jpeg',
  '$root/$directory/florence-11.jpeg',
  '$root/$directory/florence-12.jpeg',
  '$root/$directory/florence-13.jpeg',
  '$root/$directory/florence-14.jpeg',
  '$root/$directory/florence-15.jpeg',
];
